version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: pwd
      - run: ls -la
      - run: cd vscode && make --no-print-directory setup
      - run: cd vscode && make --no-print-directory test-ci
